const fs = require(`fs-extra`),
    inquirer = require(`inquirer`),
    path = require(`path`);

/**
 * Generate a deployment JSON file that will send a local compressed source to a remote AWS S3 bucket
 */
function createConfiguration() {
    const questions = [
        {
            name: `localFile`,
            message: `Path to local deployment file`,
        },
        {
            name: `s3Bucket`,
            message: `Bucket name in S3`,
        },
        {
            name: `s3Key`,
            message: `Object key in S3`,
            default: (answers) => {
                return path.basename(answers.localFile);
            },
        },
    ];

    return inquirer
        .prompt(questions)
        .then(answers => generateConfigurationFile(answers));
}

/**
 * Generate a JSON configuration file
 * @param {Object} answers - the answer object generated by inquirer.js 
 */
function generateConfigurationFile(answers) {
    // Write the file
    let configFilePath = path.join(process.cwd(), `lamb-duh.deployment.json`);

    return fs.writeFile(configFilePath, JSON.stringify(answers, null, 4));
}

module.exports.CreateDeploymentConfiguration = createConfiguration;
